# Generated by Django 6.0 on 2025-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_customuser_bio_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="asset",
            name="average_buy_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
