# Generated by Django 5.2.7 on 2025-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_asset_purchase_price_asset_average_buy_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="quantity",
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
