# Generated by Django 6.0 on 2025-12-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_asset_id_alter_customuser_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="symbol",
            new_name="coin_id",
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
