# Generated by Django 6.0 on 2025-12-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_rename_symbol_asset_coin_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
