# Generated by Django 6.0 on 2025-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_transaction_total_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="purchase_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="asset",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
