# Generated by Django 6.0 on 2025-12-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_rename_purchase_date_asset_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="realized_profit_loss",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
