# Generated by Django 6.0 on 2025-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_asset_realized_profit_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="coin_id",
            field=models.CharField(max_length=100),
        ),
    ]
